# Generated by Django 4.2.2 on 2023-07-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='split_value',
            field=models.CharField(default='okmybad', max_length=200),
        ),
    ]
