# Generated by Django 4.2.2 on 2023-07-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_file_publicfile_folder_publicfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filename',
        ),
    ]
