# Generated by Django 4.2.2 on 2023-07-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_userprofile_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='image',
        ),
    ]
